# Generated by Django 5.0.7 on 2024-07-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='communication_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hearing_impaired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
